apiVersion: v1
kind: Service
metadata:
  creationTimestamp: 2019-03-24T03:03:12Z
  labels:
    run: ccminiprojecttired
  name: ccminiprojecttired
  namespace: default
  resourceVersion: "274889"
  selfLink: /api/v1/namespaces/default/services/ccminiprojecttired
  uid: 5c46068d-4de1-11e9-9f2f-42010a800076
spec:
  clusterIP: 10.11.246.3
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 31563
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    run: ccminiprojecttired
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 104.198.30.80
